name: Xbox SOH Builder

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag Name'
        required: true
        default: 'v1.0.0'
      package_name:
        description: 'Package Name'
        required: true
        default: 'Xbox_SOH'

jobs:
  build:
    runs-on: ${{ (vars.WINDOWS_RUNNER && fromJSON(vars.WINDOWS_RUNNER)) || 'windows-latest' }}

    env:
      Platform: x64
      Configuration: Release
      BuildMode: SideLoadOnly
      AppxBundle: Never
      CMakeGenerator: Ninja
      VCPKG_ROOT: D:/a/vcpkg
      SourceDir: "${{ github.workspace }}/soh-uwp"
      BuildDir: "${{ github.workspace }}/build-uwp"
      PackageOutputRootDir: "${{ github.workspace }}/AppPackages"
      PackageOutputDir: "${{ github.workspace }}/AppPackages/${{ github.event.inputs.package_name }}_${{ github.event.inputs.tag_name }}"

    steps:
      - name: Install Dependencies
        if: ${{ !vars.WINDOWS_RUNNER }}
        run: |
          choco install ninja
          Remove-Item -Path "C:\ProgramData\Chocolatey\bin\ccache.exe" -Force -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup CCache
        uses: dcvz/ccache-action@27b9f33213c0079872f064f6b6ba0233dfa16ba2
        with:
          key: ${{ runner.os }}-ccache

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: |
          set $env:PATH="$env:USERPROFILE/.cargo/bin;$env:PATH"
          cmake -S "$env:SourceDir" -B "$env:BuildDir" -G Ninja `
            -DCMAKE_MAKE_PROGRAM=ninja `
            -DCMAKE_BUILD_TYPE=$env:Configuration `
            -DCMAKE_C_COMPILER_LAUNCHER=ccache `
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
        shell: pwsh

      - name: Generate Self-Signed Certificate
        id: generate_cert
        run: |
          $cert = New-SelfSignedCertificate -CertStoreLocation "Cert:\CurrentUser\My" -Subject "CN=SOH_Cert" -KeyAlgorithm RSA -KeyLength 2048 -Provider "Microsoft Enhanced RSA and AES Cryptographic Provider" -KeyExportPolicy Exportable -NotAfter (Get-Date).AddYears(1) -Type CodeSigningCert
          echo "THUMBPRINT=$($cert.Thumbprint)" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Build UWP App
        run: |
          cmake --build "$env:BuildDir" --config $env:Configuration --parallel 10
        shell: pwsh    

      - name: Package UWP Build
        run: |
          mkdir soh-uwp
          mv "$env:BuildDir/x64/Release/soh.exe" soh-uwp/soh.exe
          mkdir soh-uwp/debug
          mkdir soh-uwp/mods
          New-Item soh-uwp/mods/custom_otr_files_go_here.txt -type file
          mv "$env:BuildDir/x64/Release/soh.pdb" soh-uwp/debug/soh.pdb
          mv "$env:SourceDir/README.md" soh-uwp/readme.txt
          mv "$env:BuildDir/gamecontrollerdb.txt" soh-uwp/gamecontrollerdb.txt
          mv "$env:BuildDir/x64/Release/assets" soh-uwp
        shell: pwsh

      - name: Download soh.otr
        uses: actions/download-artifact@v4
        with:
          name: soh.otr
          path: soh-uwp

      - name: Create Archive
        run: |
          Compress-Archive -Path "soh-uwp\*" -DestinationPath "$env:PackageOutputRootDir\SOH_Archive.zip"
        shell: pwsh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: soh-uwp
          path: ${{ env.PackageOutputRootDir }}/SOH_Archive.zip
